#!/usr/local/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'ryu==4.30','console_scripts','ryu-manager'
__requires__ = 'ryu==4.30'
import re
import sys
import ptvsd
from pkg_resources import load_entry_point

if __name__ == '__main__':
    address = ('0.0.0.0', 3000)
    ptvsd.enable_attach(address)
    ptvsd.wait_for_attach()
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ryu==4.30', 'console_scripts', 'ryu-manager')()
    )
