#!/bin/bash

# Snort rule configuration

cp /src/snort/snort.conf /etc/snort
cp /src/snort/blackbox.rules /etc/snort/rules

# Starting Ryu controller

debug_mode=false
while getopts ":d" opt; do
  case ${opt} in
    d )
      debug_mode=true
      ;;
    \? )
      echo "Invalid option. Usage: startblackbox [-d]"
      exit 1
      ;;
  esac
done

comm="xterm -geometry +1100+350 -e "
if [ "$debug_mode" = true ] ; then
    comm+="python -m ptvsd --host 0.0.0.0 --port 3000 "
fi
comm+="./usr/local/bin/ryu-manager --verbose --enable-debugger src/snort_learning_switch.py"
$comm &

# Starting Mininet

service openvswitch-switch start
xterm -geometry +600+350 -e python2 src/start_mininet.py &

# Starting bash

xterm -geometry +100+350 -e /bin/bash